// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAurtu_ySjNQZOIHwiJTpSQQjhWL9fSK3Y',
    appId: '1:263996116320:web:630a1c54ca1f478e856205',
    messagingSenderId: '263996116320',
    projectId: 'newsme-98083',
    authDomain: 'newsme-98083.firebaseapp.com',
    databaseURL: 'https://newsme-98083-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newsme-98083.appspot.com',
    measurementId: 'G-Y29WTG14F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbkR-JXPJNmpwMSRMx9NvwHZ7jOBBI_vM',
    appId: '1:263996116320:android:2ee2e1dcd49c2a2b856205',
    messagingSenderId: '263996116320',
    projectId: 'newsme-98083',
    databaseURL: 'https://newsme-98083-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newsme-98083.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrTolV41-hFviJ9M_TFNsKYGiqQZrG8Sk',
    appId: '1:263996116320:ios:87d8cee68196ed9a856205',
    messagingSenderId: '263996116320',
    projectId: 'newsme-98083',
    databaseURL: 'https://newsme-98083-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newsme-98083.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrTolV41-hFviJ9M_TFNsKYGiqQZrG8Sk',
    appId: '1:263996116320:ios:87d8cee68196ed9a856205',
    messagingSenderId: '263996116320',
    projectId: 'newsme-98083',
    databaseURL: 'https://newsme-98083-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newsme-98083.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAurtu_ySjNQZOIHwiJTpSQQjhWL9fSK3Y',
    appId: '1:263996116320:web:b6052b3b8a5c85ad856205',
    messagingSenderId: '263996116320',
    projectId: 'newsme-98083',
    authDomain: 'newsme-98083.firebaseapp.com',
    databaseURL: 'https://newsme-98083-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newsme-98083.appspot.com',
    measurementId: 'G-P1X2QLRLD6',
  );
}
